import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:tray_manager/tray_manager.dart';

import '../../ui/core/strings/app_strings.dart';
import 'desktop_window_service.dart';
import 'window_mode.dart';

/// The little pixel heart in the system tray — Kehai's real home on desktop.
///
/// The window collapses and expands; the tray icon is the thing that's
/// always there. Left click toggles the card ⇄ panel, and the menu is the
/// only place that can actually end the app.
///
/// No-op off Windows/Linux, like everything else in this folder.
class KehaiTray with TrayListener {
  KehaiTray._();

  static final KehaiTray instance = KehaiTray._();

  /// Menu item keys — also what [onTrayMenuItemClick] switches on.
  static const _expandKey = 'expand';
  static const _miniKey = 'mini';
  static const _quitKey = 'quit';

  /// Windows wants a real .ico; GTK's status icon takes the PNG. Both are
  /// generated by tool/generate_tray_icon.py and live in flutter_assets, the
  /// root tray_manager resolves icon paths against.
  static String get iconPath => Platform.isWindows
      ? 'assets/tray/kehai_heart.ico'
      : 'assets/tray/kehai_heart.png';

  WindowModeController? _mode;
  bool _ready = false;

  Future<void> bootstrap(WindowModeController mode) async {
    if (!DesktopWindowService.isSupported || _ready) return;
    _mode = mode;
    trayManager.addListener(this);

    // Each step is attempted on its own. tray_manager implements a different
    // subset per platform (setToolTip and popUpContextMenu are Windows/macOS
    // only, and throw MissingPluginException on Linux) — losing the hover
    // text must not cost us the menu, which is the only way to quit.
    final iconShown = await _attempt(
      'icon',
      () => trayManager.setIcon(iconPath),
    );
    if (!iconShown) return;

    if (_supportsToolTip) {
      await _attempt(
        'tooltip',
        () => trayManager.setToolTip(AppStrings.trayTooltip),
      );
    }
    await _attempt('menu', () => trayManager.setContextMenu(_menu()));

    // The icon has to be gone before the process is, or Windows leaves a
    // ghost heart in the tray until you wave the mouse over it.
    DesktopWindowService.instance.beforeQuit = _teardown;
    _ready = true;
  }

  /// GTK's status icon has no hover text, and no way to pop its own menu on
  /// demand — it shows the menu on click by itself.
  static bool get _supportsToolTip => !Platform.isLinux;

  Future<bool> _attempt(String what, Future<void> Function() action) async {
    try {
      await action();
      return true;
    } catch (error) {
      debugPrint('tray $what unavailable: $error');
      return false;
    }
  }

  Menu _menu() => Menu(
    items: [
      MenuItem(key: _expandKey, label: AppStrings.trayOpen),
      MenuItem(key: _miniKey, label: AppStrings.trayMini),
      MenuItem.separator(),
      MenuItem(key: _quitKey, label: AppStrings.trayQuit),
    ],
  );

  Future<void> _teardown() async {
    try {
      trayManager.removeListener(this);
      await trayManager.destroy();
    } catch (error) {
      debugPrint('tray teardown failed: $error');
    }
  }

  /// Left click. On Windows this fires on the icon itself; on Linux the
  /// AppIndicator/StatusNotifier host usually shows the menu instead and
  /// never sends this — which is why every action is in the menu too.
  @override
  void onTrayIconMouseDown() {
    _mode?.toggle();
  }

  /// Windows only shows the context menu if we ask it to; the Linux status
  /// icon pops its own and has no popUpContextMenu implementation at all.
  @override
  void onTrayIconRightMouseDown() {
    if (Platform.isLinux) return;
    trayManager.popUpContextMenu();
  }

  @override
  void onTrayMenuItemClick(MenuItem menuItem) {
    final mode = _mode;
    if (mode == null) return;
    switch (menuItem.key) {
      case _expandKey:
        mode.expand();
      case _miniKey:
        mode.collapse();
      case _quitKey:
        mode.quit();
    }
  }
}
