import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:tray_manager/tray_manager.dart';

import '../../ui/core/strings/app_strings.dart';
import 'autostart_service.dart';
import 'desktop_window_service.dart';
import 'prefs_service.dart';
import 'update_service.dart';
import 'window_mode.dart';

/// The little pixel heart in the system tray — Kehai's real home on desktop.
///
/// The window collapses and expands; the tray icon is the thing that's
/// always there. Left click toggles the card ⇄ panel, and the menu is the
/// only place that can actually end the app.
///
/// No-op off Windows/Linux, like everything else in this folder.
class KehaiTray with TrayListener {
  KehaiTray._();

  static final KehaiTray instance = KehaiTray._();

  /// Menu item keys — also what [onTrayMenuItemClick] switches on.
  static const _expandKey = 'expand';
  static const _miniKey = 'mini';
  static const _autostartKey = 'autostart';
  static const _oledCareKey = 'oled_care';
  static const _updateKey = 'update';
  static const _checkUpdatesKey = 'check_updates';
  static const _quitKey = 'quit';

  /// Windows wants a real .ico; GTK's status icon takes the PNG. Both are
  /// generated by tool/generate_tray_icon.py and live in flutter_assets, the
  /// root tray_manager resolves icon paths against.
  static String get iconPath => Platform.isWindows
      ? 'assets/tray/kehai_heart.ico'
      : 'assets/tray/kehai_heart.png';

  WindowModeController? _mode;
  PrefsService? _prefs;
  UpdateService? _updates;
  bool _ready = false;

  /// The version the menu currently advertises, so the menu is only pushed
  /// back to the OS when that actually changes — [UpdateService] notifies on
  /// every download tick, and re-sending the whole menu 100 times during a
  /// download would make the tray flicker for nothing.
  String? _shownUpdateVersion;

  Future<void> bootstrap(WindowModeController mode) async {
    if (!DesktopWindowService.isSupported || _ready) return;
    _mode = mode;
    // Read once up front so the checkbox's very first render already shows
    // the right state — the menu below is built off this, not fetched on
    // demand, since tray_manager builds it synchronously.
    _prefs = await PrefsService.create();
    trayManager.addListener(this);

    // Each step is attempted on its own. tray_manager implements a different
    // subset per platform (setToolTip and popUpContextMenu are Windows/macOS
    // only, and throw MissingPluginException on Linux) — losing the hover
    // text must not cost us the menu, which is the only way to quit.
    final iconShown = await _attempt(
      'icon',
      () => trayManager.setIcon(iconPath),
    );
    if (!iconShown) return;

    if (_supportsToolTip) {
      await _attempt(
        'tooltip',
        () => trayManager.setToolTip(AppStrings.trayTooltip),
      );
    }
    await _attempt('menu', () => trayManager.setContextMenu(_menu()));

    // The icon has to be gone before the process is, or Windows leaves a
    // ghost heart in the tray until you wave the mouse over it.
    DesktopWindowService.instance.beforeQuit = _teardown;
    _ready = true;
  }

  /// GTK's status icon has no hover text, and no way to pop its own menu on
  /// demand — it shows the menu on click by itself.
  static bool get _supportsToolTip => !Platform.isLinux;

  Future<bool> _attempt(String what, Future<void> Function() action) async {
    try {
      await action();
      return true;
    } catch (error) {
      debugPrint('tray $what unavailable: $error');
      return false;
    }
  }

  /// Points the menu at the app's [UpdateService] once the composition root
  /// has one (the tray is bootstrapped before [AppController] exists — see
  /// main.dart). Safe to call off desktop: without a bootstrap there is no
  /// menu to refresh.
  void attachUpdates(UpdateService updates) {
    if (_updates != null) return;
    _updates = updates;
    updates.addListener(_onUpdatesChanged);
    _shownUpdateVersion = updates.hasUpdate ? updates.availableVersion : null;
    // Unconditional: the menu built during bootstrap had no service to ask,
    // so it's missing "check for updates" even when nothing else changed.
    _pushMenu();
  }

  void _onUpdatesChanged() {
    final version = _updates?.hasUpdate == true
        ? _updates?.availableVersion
        : null;
    if (version == _shownUpdateVersion) return;
    _shownUpdateVersion = version;
    _pushMenu();
  }

  void _pushMenu() {
    if (!_ready) return;
    unawaited(_attempt('menu', () => trayManager.setContextMenu(_menu())));
  }

  /// The update entry only exists while there *is* an update — a permanent
  /// "you're up to date" line would be one more thing to read past every
  /// time the menu opens. "check for updates" stays, because a manual check
  /// is the only way to not wait up to 24 h.
  @visibleForTesting
  Menu buildMenu() => _menu();

  Menu _menu() {
    final updates = _updates;
    final version = updates?.hasUpdate == true
        ? updates?.availableVersion
        : null;
    return Menu(
      items: [
        MenuItem(key: _expandKey, label: AppStrings.trayOpen),
        MenuItem(key: _miniKey, label: AppStrings.trayMini),
        if (version != null) ...[
          MenuItem.separator(),
          MenuItem(key: _updateKey, label: AppStrings.trayUpdate(version)),
        ],
        MenuItem.separator(),
        MenuItem.checkbox(
          key: _autostartKey,
          label: AppStrings.trayAutostart,
          checked: _prefs?.autostartEnabled ?? false,
        ),
        MenuItem.checkbox(
          key: _oledCareKey,
          label: AppStrings.trayOledCare,
          checked: _prefs?.oledCareEnabled ?? false,
        ),
        if (updates?.isEnabled ?? false)
          MenuItem(key: _checkUpdatesKey, label: AppStrings.trayCheckUpdates),
        MenuItem(key: _quitKey, label: AppStrings.trayQuit),
      ],
    );
  }

  Future<void> _teardown() async {
    try {
      _updates?.removeListener(_onUpdatesChanged);
      trayManager.removeListener(this);
      await trayManager.destroy();
    } catch (error) {
      debugPrint('tray teardown failed: $error');
    }
  }

  /// Left click. On Windows this fires on the icon itself; on Linux the
  /// AppIndicator/StatusNotifier host usually shows the menu instead and
  /// never sends this — which is why every action is in the menu too.
  @override
  void onTrayIconMouseDown() {
    _mode?.toggle();
  }

  /// Windows only shows the context menu if we ask it to; the Linux status
  /// icon pops its own and has no popUpContextMenu implementation at all.
  @override
  void onTrayIconRightMouseDown() {
    if (Platform.isLinux) return;
    trayManager.popUpContextMenu();
  }

  @override
  void onTrayMenuItemClick(MenuItem menuItem) {
    final mode = _mode;
    if (mode == null) return;
    switch (menuItem.key) {
      case _expandKey:
        mode.expand();
      case _miniKey:
        mode.collapse();
      case _autostartKey:
        // Mutating .checked here (rather than after the fact) is what tells
        // tray_manager's own click handler the state changed, so it pushes
        // the refreshed menu back to the OS on its own — see
        // TrayManager._methodCallHandler's oldChecked/newChecked diff.
        final enabled = !(menuItem.checked ?? false);
        menuItem.checked = enabled;
        unawaited(_setAutostart(enabled));
      case _oledCareKey:
        final enabled = !(menuItem.checked ?? false);
        menuItem.checked = enabled;
        unawaited(DesktopWindowService.instance.setOledCareEnabled(enabled));
      case _updateKey:
        // Downloads, verifies, swaps, relaunches — the app quits on its own
        // partway through (see [DesktopUpdateInstaller.apply]).
        unawaited(_updates?.startUpdate() ?? Future<void>.value());
      case _checkUpdatesKey:
        unawaited(
          _updates?.checkNow(manual: true) ?? Future<void>.value(),
        );
      case _quitKey:
        mode.quit();
    }
  }

  /// Persists the choice first (so the checkbox never lies about what's
  /// saved even if the OS call below fails) and then asks the OS to
  /// actually do it — see [AutostartService] for the per-platform mechanics
  /// and the honest Linux/WSLg caveat.
  Future<void> _setAutostart(bool enabled) async {
    await _prefs?.setAutostartEnabled(enabled);
    final ok = enabled
        ? await AutostartService.instance.enable()
        : await AutostartService.instance.disable();
    if (!ok) {
      debugPrint('autostart ${enabled ? 'enable' : 'disable'} did not confirm success');
    }
  }
}
